version: "3.9"
services:
  wave_web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DEVELOPMENT : 0
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6380"